language: node_js

node_js:
  - node
  - lts/*

jobs:
  include:
    - stage: lint
      script:
        - prettier --check "**/*.{js, jsx, ts, tsx, json, css, md}"
        - commitlint-travis
    - stage: test
      script:
        - npm test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      script:
        - webpack
        - semantic-release
      after_sucess: skip

stages:
  - lint
  - test
  - name: release
    if: branch = master AND type = push AND fork = false
