language: node_js

node_js:
  - node
  - lts/*

jobs:
  include:
    - stage: lint
      script:
        - commitlint-travis
    - stage: test
      script:
        - npm test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    # - stage: release
    #   script:
    #     - npm run semantic-release
    #   after_sucess: skip

stages:
  - lint
  - test
  # - name: release
  #   if: branch = master AND type = push AND fork = false
